<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MifielAPI</RootNamespace>
    <AssemblyName>MifielAPI</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageId>MifielAPIClient</PackageId>
    <Version>1.0.0</Version>
    <Authors>Genaro Madrid, Juan Antonio Zavala Aguilar</Authors>
    <Company>mifiel.com</Company>
    <Description>Mifiel provide a simple and robust RESTful API enabling any service or company operating in Mexico to integrate electronic signatures (using the FIEL) into their workflow.

Through Mifiel’s API, you can easily manage documents and certificates within your Mifiel account</Description>
    <PackageProjectUrl>https://github.com/Mifiel/csharp-api-client</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Mifiel/csharp-api-client</RepositoryUrl>
    <PackageTags>mifiel;electronic-signatures</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Title>Mifiel API Client for C#</Title>
    <Summary>C# SDK for mifiel.com.</Summary>
    <IsPackable>true</IsPackable>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MifielAPITests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
